networks:
  l4d2-test-network:
    driver: bridge
  l4d2-game-network:
    external: true
    name: l4d2-server-next_l4d2-network

services:
  l4d2-test-manager:
    image: laoyutang/l4d2-manager-next:latest
    container_name: l4d2-test-manager
    restart: unless-stopped
    ports:
      - "27021:27020"
    volumes:
      - /opt/l4d2_server_test/left4dead2:/left4dead2
      - /opt/l4d2_server_test/plugins:/plugins
      - /proc:/host/proc:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - l4d2-test-network
      - l4d2-game-network
    environment:
      - L4D2_RESTART_BY_RCON=true
      - L4D2_MANAGER_PASSWORD=BHomFU7aB7KTGD#gYu
      - L4D2_RCON_URL=l4d2-server-test:27015
      - L4D2_RCON_PASSWORD=dy$RYiYZP5h2RZ2jp4
      - L4D2_GAME_PATH=/left4dead2
